profiles:
  sasol-laptop:
    dotfiles:
    - inst_spotify_sh
    - inst_git_sh
    - inst_vscode_sh
    - f_vscode_settings
    - inst_tldr_sh
    - inst_fzf_sh
    - inst_diff_so_fancy_sh
    - inst_bashit_sh
    - d_remmina
    - d_remmina_connections
    - d_resources
    - f_bashrc
    - f_profile
    - f_xsessionrc
    - f_initrc__
    - f_initrc
    - f_zshrc
    - d_bashdrop
    - d_bin
    - f_jetbrains
    - inst_jetbrains_sh
    - inst_sdkman_sh
    - d_sdkman
    - inst_sdkman_tools_sh

variables:
  base_user: sasol
  version_vagrant: 2.2.5
config:
  dotpath: dotfiles
  backup: true
  create: true
  import_configs:
  - tmp/install.yaml  
dotfiles:
  d_remmina:
    dst: ~/.config/remmina
    src: .config/remmina
  d_remmina_connections:
    dst: ~/.local/share/remmina
    src: .local/share/remmina
  d_resources:
    dst: ~/.dotdrop-install/resources
    src: install/resources
  f_bashrc:
    dst: ~/.bashrc
    src: .bashrc
  f_profile:
    dst: ~/.profile
    src: .profile
  f_xsessionrc:
    dst: ~/.xsessionrc
    src: .xsessionrc
  f_initrc:
    dst: ~/.xinitrc
    src: .xinitrc 
  f_initrc__:
    dst: ~/.xinitrc__
    src: .xinitrc__   
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc
  d_bashdrop:
    dst: ~/.bashdrop
    src: .bashdrop
  d_bin:
    dst: ~/.bin
    src: .bin
  f_jetbrains:
    dst: ~/.local/share/JetBrains/Toolbox/.settings.json
    src: .local/share/JetBrains/Toolbox/.settings.json
  f_vscode_settings:
    dst: ~/.config/Code/User/settings.json
    src: .config/Code/User/settings.json
  d_sdkman:
    dst: ~/.sdkman/etc
    src: .sdkman/etc
